import fs from "node:fs";
import os from "node:os";
import path from "node:path";

/** Where SaaS state (tenants, platform switches, usage, per-tenant CRM data) lives. */
export function saasDataDir(): string {
  return process.env.XCODER_SAAS_DATA_DIR || path.join(os.homedir(), ".xcoder", "saas");
}

export function readJson<T>(file: string, fallback: T): T {
  try { return JSON.parse(fs.readFileSync(file, "utf8")) as T; } catch { return fallback; }
}

/** Atomic write (temp file + rename), owner-only permissions: a crash can never leave a half-written store. */
export function writeJsonAtomic(file: string, data: unknown): void {
  fs.mkdirSync(path.dirname(file), { recursive: true, mode: 0o700 });
  const tmp = `${file}.${process.pid}.${Date.now()}.tmp`;
  fs.writeFileSync(tmp, JSON.stringify(data, null, 2), { encoding: "utf8", mode: 0o600 });
  fs.renameSync(tmp, file);
}

/** Tenant ids are generated by us, but anything that becomes a path segment is re-validated. */
export const TENANT_ID_RE = /^[a-z0-9][a-z0-9-]{1,40}$/;
export function tenantDir(tenantId: string): string {
  if (!TENANT_ID_RE.test(tenantId)) throw new Error("invalid tenant id");
  return path.join(saasDataDir(), "tenants", tenantId);
}
